{
 "title": "Vintage Story Server Metrics",
 "tags": [
  "Vintagestory",
  "game"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "query": "serverstats" },
   { "name": "ping", "query": "0.500" },
   { "name": "logtickMs", "query": "100" },
   {
    "name": "player",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"${server}\",\n  tag: \"player\",\n  predicate: (r) => true,\n  start: -1y\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Player Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "First time online",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${server}\")\n  |> range(start: -10y, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"online\")\n  |> filter(fn: (r) => r[\"player\"] == \"${player}\")\n  |> first()\n  |> keep(columns: [\"_time\"])"
      }
     ]
    },
    {
     "title": "Last time online",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${server}\")\n  |> range(start: -10y, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"online\")\n  |> filter(fn: (r) => r[\"player\"] == \"${player}\")\n  |> last()\n  |> keep(columns: [\"_time\"])"
      }
     ]
    },
    {
     "title": "Total Playtime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"$server\")\n  |> range(start: -10y, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"online\")\n  |> filter(fn: (r) => r[\"player\"] == \"${player}\")\n  |> count()\n  |> map(fn: (r) => ({ r with\n    _value: r._value * 10\n  }))\n  |> group()\n  |> keep(columns: [\"player\", \"_value\"])\n  |> sort(columns: [\"_value\"], desc: true)"
      }
     ]
    },
    {
     "title": "Total Deaths",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 11, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"$server\")\n  |> range(start: -10y, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deaths\")\n  |> filter(fn: (r) => r[\"player\"] == \"${player}\")\n  |> count()\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Quick Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"errors\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> count()\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Warning count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warnings\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> count()\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory\")\n"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"clients\")\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"threads\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Full",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ticktime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"l2avgticktime\")\n"
    }
   ]
  },
  {
   "title": "Ticks/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"l2stickspersec\")\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory\" or r[\"_measurement\"] == \"memoryManaged\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n"
    }
   ]
  },
  {
   "title": "Generating Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"generatingChunks\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities\" or r[\"_measurement\"] == \"entitiesActive\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"chunks\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n"
    }
   ]
  },
  {
   "title": "Network: Packets/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"packetspresec\")\n"
    }
   ]
  },
  {
   "title": "Network: Kb/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kilobytespersec\")\n"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"clients\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deaths\")\n"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"errors\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warnings\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n"
    }
   ]
  },
  {
   "title": "Overloaded warnings",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"overloadwarnings\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n"
    }
   ]
  },
  {
   "title": "Players",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Playtime",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"online\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> count()\n  |> map(fn: (r) => ({ r with\n    _value: r._value * 10\n  }))\n  |> group()\n  |> keep(columns: [\"player\", \"_value\"])\n  |> sort(columns: [\"_value\"], desc: true)"
    }
   ]
  },
  {
   "title": "Player Ping",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"online\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_value\"] < $ping)\n"
    }
   ]
  },
  {
   "title": "Logticks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logticks",
   "type": "logs",
   "gridPos": { "h": 26, "w": 11, "x": 0, "y": 105 },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"logticks\")\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "Logticks filtered by logtickMs",
   "type": "logs",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 105 },
   "targets": [
    {
     "query": "from(bucket: \"$server\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"logticks\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.ms > ${logtickMs})"
    }
   ]
  }
 ]
}